#!/usr/bin/env php
<?php
if (file_exists(__DIR__ . '/../autoload.php')) {
    $autoload = __DIR__ . '/../autoload.php';
} else {
    $autoload = '@php_dir@/PEAR2/Autoload.php';
}

require_once $autoload;

$cli = new \Pyrus\SimpleChannelServer\CLI();
$cli->process();
